# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            USER: 'sail'
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/usr/bin/docker:/usr/bin/docker'
            - '/usr/local/bin/docker-compose:/usr/local/bin/docker-compose'
            - '/etc/group:/etc/group'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    myadmin:
        image: 'phpmyadmin:latest'
        ports:
          - '8080:80'
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
          - "mysql:db"
        depends_on:
          - mysql
        networks:
          - sail
    gtftk:
        build:
            context: .
            dockerfile: Dockerfile-pygtftk-conda
        image: 'gtftk:staging'
        ports:
            - '6869:6869'
        volumes:
            - './pygtftk_results:/pygtftk'
        networks:
            - sail
    shiny:
        build:
            context: .
            dockerfile: Dockerfile-shiny
        image: 'shiny-app:latest'
        ports:
            - '7775:7775'
        volumes:
            - './app/Shiny:/shiny'
            - './pygtftk_results:/shiny/pygtftk_results'
        networks:
            - sail
        


networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-shiny:
        driver: local
