proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: simple
  admin-groups: scientists
  container-wait-time: 60000
  users:
  - name: Hamma
    password: 12345678
    groups: scientists
  - name: jeff
    password: password
    groups: mathematicians
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: OLOGRAM dashboard
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R","-e","shinyproxy::run_01_hello()"]
    container-image: shiny-app
    access-groups: [scientists, mathematicians]
  - id: 06_tabsets
    container-cmd: ["sg","docker","-c","'R","-e","shinyproxy::run_06_tabsets()'"]
    container-image: openanalytics/shinyproxy-demo
    access-groups: scientists

logging:
  file:
    name: shinyproxy.log
